---
title: "Question12"
author: "Morgann Plante"
date: "11/23/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(shiny)

d = read_csv('final.csv')

variables_names = names(d)

ui <- navbarPage("Navbar!",
           tabPanel("Numeric and Categorical Variable Graphs",
                    
                    sidebarLayout(
                      sidebarPanel(
                        
                        checkboxGroupInput(inputId = "raceethn", 
                                           label = h3("Select Race to compare"),
                                           choices = names(table(d$raceethn)), 
                                           selected = c(1,2),
                                           inline = TRUE),
                        
                        selectInput(
                          inputId ="var1",
                          label = "Select a Numeric Variables",
                          choices = variables_names, 
                          selected = "er_chrg"),
                        
                        sliderInput(inputId = "age",
                                    "Select Age Range:",
                                    min = min(d$age, na.rm=TRUE),
                                    max = max(d$age, na.rm=TRUE),
                                    value= c(0,50)),
                        
                        radioButtons(inputId = "plot_choice", 
                                     label = h3("Select Plot:"),
                                     choices = c("Box Plot" = "box",
                                                 "Density Plot" = "Density"),
                                     selected = 'box')
                        ),
                      
                      mainPanel(
                        plotOutput(outputId = 'show_plot')
                      )
                    )
           ),
           
           
           tabPanel("Categorical Variable Graphs",
                    
                    sidebarLayout(
                      sidebarPanel(
                        
                        checkboxGroupInput(inputId = "raceethn1", 
                                           label = h3("Select Race to compare"),
                                           choices = names(table(d$raceethn)), 
                                           selected = c(1,2),
                                           inline = TRUE),
                        
                        selectInput(
                          inputId ="var11",
                          label = "Select a Numeric Variable",
                          choices = variables_names, 
                          selected = "er_chrg"),
                        
                        selectInput(
                          inputId ="var21",
                          label = "Select a Categorical Variable",
                          choices = variables_names, 
                          selected = "provider"),
                        
                        sliderInput(inputId = "age1",
                                    "Select Age Range:",
                                    min = min(d$age, na.rm=TRUE),
                                    max = max(d$age, na.rm=TRUE),
                                    value= c(0,50)),
                        
                        radioButtons(inputId = "plot_choice1", 
                                     label = h3("Select Plot:"),
                                     choices = c("Bar Plot" = "bar",
                                                 "Histogram" = "histogram"),
                                     selected = 'bar')
                        ),
                      
                      mainPanel(
                        plotOutput(outputId = 'show_plot2')
                      )
                    )
           )
)

# server is a function! 
server <- function(input, output) {
  
  
  output$show_plot <- renderPlot({
    
    v1 = input$var1
    v2 = input$var2
    raceethn = input$raceethn
    age = input$age
    
    
    library(ggplot2)
    
    d <- d %>% filter(raceethn %in% input$raceethn, 
                      age>input$age[1],
                      age<input$age[2])
    
    if(input$plot_choice == 'box')
      
    {
      ggplot(d, aes(x = d[[v1]], color = as.factor(raceethn)))+
        geom_boxplot()+
        labs(x = v1, color = d$raceethn)
    }
    
    else
    {
      ggplot(d, aes(x = d[[v1]], color = as.factor(raceethn)))+
        geom_density()+
        labs(x = d[[v1]], color = d$raceethn)
    }
    
  })
  
  output$show_plot2 <- renderPlot({
    
    v11 = input$var11
    v21 = input$var21
    raceethn1 = input$raceethn1
    age1 = input$age1
    
    
    library(ggplot2)
    
    d <- d %>% filter(raceethn %in% input$raceethn1, 
                      age>input$age1[1],
                      age<input$age1[2])
    
    if(input$plot_choice1 == 'bar')
      
    {
      ggplot(d, aes(x = as.factor(d[[v21]]), fill = as.factor(d$raceethn)))+
        geom_bar()+
        labs(x = v21, fill = d$raceethn)
    }
    
    else
    {
      ggplot(d, aes(x = d[[v11]], fill = as.factor(d$raceethn)))+
        geom_histogram()+
        labs(x = d[[v11]], fill = d$raceethn)
    
    }
  })
  
}
# app
shinyApp(ui = ui, server = server)
```

